export const currencyNames = {
  'USD': 'US Dollar',
  'EUR': 'Euro',
  'GBP': 'British Pound',
  'JPY': 'Japanese Yen',
  'AUD': 'Australian Dollar',
  'CAD': 'Canadian Dollar',
  'CHF': 'Swiss Franc',
  'CNY': 'Chinese Yuan',
  'SEK': 'Swedish Krona',
  'NZD': 'New Zealand Dollar',
  'MXN': 'Mexican Peso',
  'SGD': 'Singapore Dollar',
  'HKD': 'Hong Kong Dollar',
  'NOK': 'Norwegian Krone',
  'KRW': 'South Korean Won',
  'TRY': 'Turkish Lira',
  'RUB': 'Russian Ruble',
  'INR': 'Indian Rupee',
  'BRL': 'Brazilian Real',
  'ZAR': 'South African Rand',
  'DKK': 'Danish Krone',
  'PLN': 'Polish Zloty',
  'THB': 'Thai Baht',
  'IDR': 'Indonesian Rupiah',
  'HUF': 'Hungarian Forint',
  'CZK': 'Czech Koruna',
  'ILS': 'Israeli Shekel',
  'CLP': 'Chilean Peso',
  'PHP': 'Philippine Peso',
  'AED': 'UAE Dirham',
  'COP': 'Colombian Peso',
  'SAR': 'Saudi Riyal',
  'MYR': 'Malaysian Ringgit',
  'RON': 'Romanian Leu',
  'ARS': 'Argentine Peso',
  'VND': 'Vietnamese Dong',
  'BGN': 'Bulgarian Lev',
  'HRK': 'Croatian Kuna',
  'ISK': 'Icelandic Krona',
  'PKR': 'Pakistani Rupee',
  'EGP': 'Egyptian Pound',
  'NGN': 'Nigerian Naira',
  'KES': 'Kenyan Shilling',
  'UAH': 'Ukrainian Hryvnia',
  'PEN': 'Peruvian Sol',
  'MAD': 'Moroccan Dirham',
  'BDT': 'Bangladeshi Taka',
  'QAR': 'Qatari Riyal',
  'KWD': 'Kuwaiti Dinar',
  'OMR': 'Omani Rial',
  'JOD': 'Jordanian Dinar',
  'BHD': 'Bahraini Dinar',
  'LKR': 'Sri Lankan Rupee',
  'MMK': 'Myanmar Kyat',
  'NPR': 'Nepalese Rupee',
  'AFN': 'Afghan Afghani',
  'IRR': 'Iranian Rial',
  'IQD': 'Iraqi Dinar',
  'LBP': 'Lebanese Pound',
  'SYP': 'Syrian Pound',
  'YER': 'Yemeni Rial',
  'TND': 'Tunisian Dinar',
  'DZD': 'Algerian Dinar',
  'LYD': 'Libyan Dinar',
  'SDG': 'Sudanese Pound',
  'ETB': 'Ethiopian Birr',
  'UGX': 'Ugandan Shilling',
  'TZS': 'Tanzanian Shilling',
  'GHS': 'Ghanaian Cedi',
  'XOF': 'West African CFA Franc',
  'XAF': 'Central African CFA Franc',
  'AOA': 'Angolan Kwanza',
  'MZN': 'Mozambican Metical',
  'ZMW': 'Zambian Kwacha',
  'MWK': 'Malawian Kwacha',
  'BWP': 'Botswana Pula',
  'NAD': 'Namibian Dollar',
  'SZL': 'Swazi Lilangeni',
  'LSL': 'Lesotho Loti',
  'MUR': 'Mauritian Rupee',
  'SCR': 'Seychellois Rupee',
  'MGA': 'Malagasy Ariary',
  'KMF': 'Comorian Franc',
  'DJF': 'Djiboutian Franc',
  'SOS': 'Somali Shilling',
  'RWF': 'Rwandan Franc',
  'BIF': 'Burundian Franc',
  'GMD': 'Gambian Dalasi',
  'SLL': 'Sierra Leonean Leone',
  'LRD': 'Liberian Dollar',
  'GNF': 'Guinean Franc',
  'CVE': 'Cape Verdean Escudo',
  'STN': 'São Tomé and Príncipe Dobra',
  'ALL': 'Albanian Lek',
  'BAM': 'Bosnia-Herzegovina Convertible Mark',
  'MKD': 'Macedonian Denar',
  'RSD': 'Serbian Dinar',
  'MDL': 'Moldovan Leu',
  'GEL': 'Georgian Lari',
  'AMD': 'Armenian Dram',
  'AZN': 'Azerbaijani Manat',
  'BYN': 'Belarusian Ruble',
  'KZT': 'Kazakhstani Tenge',
  'UZS': 'Uzbekistani Som',
  'TJS': 'Tajikistani Somoni',
  'KGS': 'Kyrgyzstani Som',
  'TMT': 'Turkmenistani Manat',
  'MNT': 'Mongolian Tugrik',
  'KHR': 'Cambodian Riel',
  'LAK': 'Lao Kip',
  'BND': 'Brunei Dollar',
  'FJD': 'Fijian Dollar',
  'PGK': 'Papua New Guinean Kina',
  'SBD': 'Solomon Islands Dollar',
  'VUV': 'Vanuatu Vatu',
  'WST': 'Samoan Tala',
  'TOP': 'Tongan Paʻanga',
  'XPF': 'CFP Franc',
  'BBD': 'Barbadian Dollar',
  'BMD': 'Bermudian Dollar',
  'BSD': 'Bahamian Dollar',
  'BZD': 'Belize Dollar',
  'DOP': 'Dominican Peso',
  'GTQ': 'Guatemalan Quetzal',
  'HNL': 'Honduran Lempira',
  'JMD': 'Jamaican Dollar',
  'NIO': 'Nicaraguan Córdoba',
  'PAB': 'Panamanian Balboa',
  'TTD': 'Trinidad and Tobago Dollar',
  'XCD': 'East Caribbean Dollar',
  'ANG': 'Netherlands Antillean Guilder',
  'AWG': 'Aruban Florin',
  'SRD': 'Surinamese Dollar',
  'GYD': 'Guyanese Dollar',
  'HTG': 'Haitian Gourde',
  'CUP': 'Cuban Peso',
  'BOB': 'Bolivian Boliviano',
  'PYG': 'Paraguayan Guarani',
  'UYU': 'Uruguayan Peso',
  'VES': 'Venezuelan Bolívar',
};